os:
  - osx
language: 
  - objective-c
compiler:
  - clang
  
before_install:
  - brew update
install:
# - brew install cmake
# - brew install boost --with-c++11
# Change this to your needs
before_script:
  - git clone https://github.com/audiofilter/spuce.git
  - cd spuce
  - mkdir build
  - cd build
  - cmake ..
  - make install
  - cd ../../
  - mkdir build
  - cd build
  - cmake ..
script: make
